Repository SoloForest/TownForest, pull requests merged in 2023-07, with the labels that each got.

#47 Enhancement41/join
  src/main/java/com/ll/townforest/boundedContext/account/controller/AccountController.java
  src/main/java/com/ll/townforest/boundedContext/account/dto/AccountDTO.java
  src/main/java/com/ll/townforest/boundedContext/account/repository/AccountRepository.java
  src/main/java/com/ll/townforest/boundedContext/account/service/AccountService.java
  src/main/resources/static/css/account.css
  src/main/resources/static/js/joinForm_validation.js
  src/main/resources/static/js/loginForm_validation.js
  src/main/resources/templates/account/join.html
  src/main/resources/templates/account/login.html
  src/test/java/com/ll/townforest/boundedContext/account/controller/AccountControllerTests.java
Labels: enhancement

#52 Enhancement51/apt account register
  src/main/java/com/ll/townforest/boundedContext/apt/controller/aptAccountController.java
  src/main/resources/static/css/form-styles.css
  src/main/resources/templates/account/join.html
  src/main/resources/templates/account/login.html
  src/main/resources/templates/aptAccount/register.html
Labels: enhancement

#49 Enhancement44/gym
  build.gradle
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/boundedContext/gym/controller/GymController.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymHistory.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymTicket.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymHistoryRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymMembershipRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymTicketRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/service/GymService.java
  src/main/resources/application-secret.yml.template
  src/main/resources/application.yml
  src/main/resources/templates/gym/fail.html
  src/main/resources/templates/gym/register.html
  src/main/resources/templates/gym/success.html
Labels: enhancement

#53 Enhancement29/vehicle
  src/main/java/com/ll/townforest/boundedContext/maintenance/controller/VehicleController.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/form/VehicleForm.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/repository/VehicleRepository.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/service/VehicleService.java
  src/main/resources/templates/maintenance/add.html
  src/main/resources/templates/maintenance/vehicle.html
Labels: enhancement

#61 Enhancement54/apt account register
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/base/rq/Rq.java
  src/main/java/com/ll/townforest/base/security/SecurityConfig.java
  src/main/java/com/ll/townforest/boundedContext/apt/DTO/AptAccountDTO.java
  src/main/java/com/ll/townforest/boundedContext/apt/controller/aptAccountController.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/AptAccountHouse.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/House.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/HouseRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountService.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/HomeController.java
  src/main/resources/templates/aptAccount/awaiting_approval.html
  src/main/resources/templates/aptAccount/register.html
Labels: enhancement

#65 Enhancement58/guest vehicle register
  src/main/java/com/ll/townforest/boundedContext/maintenance/controller/GuestVehicleController.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/form/GuestVehicleDTO.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/service/VehicleService.java
  src/main/resources/static/js/calender.js
  src/main/resources/templates/guest/car_register.html
  src/main/resources/templates/home/main.html
  src/test/java/com/ll/townforest/boundedContext/maintenance/controller/GuestVehicleControllerTests.java
Labels: enhancement

#66 Enhancement62/admin apt account
  src/main/java/com/ll/townforest/boundedContext/account/entity/Account.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountService.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/resources/templates/admin/aptAccount/management.html
Labels: enhancement

#68 Enhancement63/gym
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/base/rq/Rq.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountService.java
  src/main/java/com/ll/townforest/boundedContext/gym/controller/GymController.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymHistory.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymMembership.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymMembershipRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/service/GymService.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/java/com/ll/townforest/boundedContext/home/dto/SearchDTO.java
  src/main/resources/templates/admin/gym/gym.html
  src/main/resources/templates/admin/gym/members.html
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/gym/register.html
Labels: enhancement

#71 Enhancement69/gym
  src/main/java/com/ll/townforest/boundedContext/gym/controller/GymController.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymHistory.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymMembership.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymHistoryRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymMembershipRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/service/GymService.java
  src/main/resources/templates/gym/gym.html
  src/main/resources/templates/gym/history.html
  src/main/resources/templates/gym/pause.html
  src/test/java/com/ll/townforest/boundedContext/gym/controller/GymControllerTest.java
  src/test/java/com/ll/townforest/boundedContext/gym/service/GymServiceTest.java
Labels: enhancement

#72 Enhancement67/admin apt account house
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/base/rq/Rq.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/AptAccount.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/AptAccountHouse.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/House.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptAccountHouseRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountHouseService.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/HomeController.java
  src/main/resources/static/Logo.png
  src/main/resources/static/long_Logo.png
  src/main/resources/templates/admin/aptAccount/management.html
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/home/layout.html
Labels: enhancement

#74 Enhancement64/admin guest vehicle
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/entity/Vehicle.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/form/GuestVehicleHistory.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/repository/VehicleRepository.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/service/VehicleService.java
  src/main/resources/templates/admin/guest/vehicle.html
  src/main/resources/templates/admin/main.html
Labels: enhancement

#76 Enhancement75/guest vehicle
  src/main/java/com/ll/townforest/boundedContext/maintenance/controller/GuestVehicleController.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/repository/VehicleRepository.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/service/VehicleService.java
  src/main/resources/static/js/dateUtil.js
  src/main/resources/templates/guest/car_register.html
Labels: enhancement

#77 Enhancement70/me
  src/main/java/com/ll/townforest/base/security/SecurityConfig.java
  src/main/java/com/ll/townforest/boundedContext/account/controller/AccountController.java
  src/main/java/com/ll/townforest/boundedContext/account/entity/Account.java
  src/main/java/com/ll/townforest/boundedContext/account/service/AccountService.java
  src/main/java/com/ll/townforest/boundedContext/apt/DTO/EditForm.java
  src/main/java/com/ll/townforest/boundedContext/apt/controller/aptAccountController.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/AptAccountHouse.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptAccountHouseRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountHouseService.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountService.java
  src/main/resources/static/js/editForm_validation.js
  src/main/resources/templates/account/edit.html
  src/main/resources/templates/aptAccount/me.html
  src/main/resources/templates/home/main.html
Labels: enhancement

#84 Enhancement82/notice
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/HomeController.java
  src/main/java/com/ll/townforest/boundedContext/notice/controller/NoticeController.java
  src/main/java/com/ll/townforest/boundedContext/notice/entity/Notice.java
  src/main/java/com/ll/townforest/boundedContext/notice/repository/NoticeRepository.java
  src/main/java/com/ll/townforest/boundedContext/notice/service/NoticeService.java
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/home/layout.html
  src/main/resources/templates/home/main.html
  src/main/resources/templates/notice/detail.html
  src/main/resources/templates/notice/notice.html
  src/main/resources/templates/notice/notice_form.html
Labels: enhancement

#81 Enhancement73/gym
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/boundedContext/gym/controller/GymController.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymMembership.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymTicket.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymHistoryRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymTicketRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/service/GymService.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/java/com/ll/townforest/boundedContext/home/dto/SearchDTO.java
  src/main/java/com/ll/townforest/boundedContext/home/dto/TicketForm.java
  src/main/java/com/ll/townforest/standard/util/Ut.java
  src/main/resources/templates/admin/gym/gym.html
  src/main/resources/templates/admin/gym/history.html
  src/main/resources/templates/admin/gym/ticket/ticket.html
  src/main/resources/templates/admin/gym/ticket/ticket_form.html
  src/main/resources/templates/gym/gym.html
  src/main/resources/templates/gym/register.html
  src/test/java/com/ll/townforest/boundedContext/gym/service/GymServiceTest.java
Labels: enhancement

#86 Enhancement79/library admin
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/java/com/ll/townforest/boundedContext/library/repository/LibraryHistoryRepository.java
  src/main/java/com/ll/townforest/boundedContext/library/service/LibraryService.java
  src/main/resources/templates/admin/library/histories.html
Labels: enhancement

#85 Enhancement60/vehicle
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptAccountHouseRepository.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/controller/VehicleController.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/entity/Vehicle.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/form/VehicleForm.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/repository/VehicleRepository.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/service/VehicleService.java
  src/main/resources/templates/home/main.html
  src/main/resources/templates/maintenance/add.html
  src/main/resources/templates/maintenance/vehicle.html
Labels: enhancement

#89 게스트하우스 개발용 데이터 추가
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/House.java
Labels: enhancement

#90 Enhancement83/init data
  src/main/java/com/ll/townforest/base/initData/Prod.java
Labels: enhancement

#92 Enhancement78/withdraw
  src/main/java/com/ll/townforest/base/event/EventAccountWithdraw.java
  src/main/java/com/ll/townforest/boundedContext/account/controller/AccountController.java
  src/main/java/com/ll/townforest/boundedContext/account/service/AccountService.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/AptAccount.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/AptAccountHouse.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptAccountHouseRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountHouseService.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountService.java
  src/main/java/com/ll/townforest/boundedContext/gym/controller/GymController.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymHistory.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymMembership.java
  src/main/java/com/ll/townforest/boundedContext/gym/eventListener/GymEventListener.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymMembershipRepository.java
  src/main/java/com/ll/townforest/boundedContext/gym/service/GymService.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/resources/static/js/editForm_validation.js
  src/main/resources/templates/account/edit.html
  src/main/resources/templates/admin/aptAccount/management.html
  src/main/resources/templates/admin/gym/history.html
  src/main/resources/templates/admin/gym/members.html
  src/main/resources/templates/aptAccount/me.html
  src/main/resources/templates/gym/gym.html
  src/main/resources/templates/gym/pause.html
Labels: enhancement

#98 Enhancement96/page design
  src/main/java/com/ll/townforest/base/rq/Rq.java
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/home/layout.html
  src/main/resources/templates/home/main.html
  src/main/resources/templates/notice/detail.html
  src/main/resources/templates/notice/notice.html
  src/main/resources/templates/notice/notice_form.html
Labels: enhancement

#97 docs : readmd 완성
  images/Logo.png
  images/techStack.png
  readme.md
Labels: documentation

#93 Enhancement87/gym
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/base/initData/Prod.java
  src/main/java/com/ll/townforest/boundedContext/gym/controller/GymController.java
  src/main/java/com/ll/townforest/boundedContext/gym/service/GymService.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/templates/admin/gym/gym.html
  src/main/resources/templates/admin/gym/history.html
  src/main/resources/templates/admin/gym/members.html
  src/main/resources/templates/admin/gym/ticket/ticket.html
  src/main/resources/templates/gym/gym.html
  src/main/resources/templates/gym/history.html
  src/main/resources/templates/gym/register.html
  src/test/java/com/ll/townforest/boundedContext/gym/controller/GymControllerTest.java
Labels: enhancement

#95 Enhancement80/account
  src/main/java/com/ll/townforest/boundedContext/account/controller/AccountController.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptAccountHouseRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountHouseService.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountService.java
  src/main/java/com/ll/townforest/boundedContext/home/controller/AdminController.java
  src/main/resources/static/Logo.png
  src/main/resources/static/js/editForm_validation.js
  src/main/resources/templates/account/edit.html
  src/main/resources/templates/admin/aptAccount/management.html
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/home/main.html
Labels: enhancement

#104 enhancement88/vehicle
  src/main/java/com/ll/townforest/boundedContext/maintenance/form/VehicleForm.java
  src/main/resources/templates/maintenance/add.html
Labels: enhancement

#106 feat : 아파트 정보 등록 시 예외처리 수정
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountService.java
Labels: bug

#107 fix : admin-history 페이지 이동 안되던 버그 수정
  src/main/resources/templates/admin/gym/history.html
Labels: bug

#100 enhancement99/withdraw
  src/main/java/com/ll/townforest/boundedContext/account/service/AccountService.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptAccountHouseRepository.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/controller/VehicleController.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/repository/VehicleRepository.java
  src/main/java/com/ll/townforest/boundedContext/maintenance/service/VehicleService.java
Labels: enhancement

#109 refactor : Enum 및 Transactional 도입
  src/main/java/com/ll/townforest/boundedContext/gym/gymEnum/HistoryType.java
  src/main/java/com/ll/townforest/boundedContext/gym/gymEnum/MembershipType.java
  src/main/java/com/ll/townforest/boundedContext/gym/service/GymService.java
Labels: enhancement
