Repository SoloForest/TownForest, pull requests merged in 2023-06, with the labels that each got.

#2 docs: .github 템플릿 작성
  .github/ISSUE_TEMPLATE/issue_bug.md
  .github/ISSUE_TEMPLATE/issue_docs.md
  .github/ISSUE_TEMPLATE/issue_feat.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_docs.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_feat.md
Labels: documentation

#3 docs: template 디폴트 파일 생성
  .github/issue_template.md
  .github/pull_request_template.md
Labels: documentation

#6 Enhancement5/templates
  build.gradle
  src/main/java/com/ll/townforest/boundedContext/home/controller/HomeController.java
  src/main/resources/static/Logo.png
  src/main/resources/static/long_Logo.png
  src/main/resources/templates/home/layout.html
  src/main/resources/templates/home/main.html
Labels: enhancement

#10 Enhancement4/account
  src/main/java/com/ll/townforest/TownforestApplication.java
  src/main/java/com/ll/townforest/boundedContext/account/entity/Account.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/Apt.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/AptAccount.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/AptAccountHouse.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/House.java
Labels: enhancement

#11 feat: Vehicle 엔티티 추가
  build.gradle
  src/main/java/com/ll/townforest/boundedContext/maintenance/entity/Vehicle.java
Labels: enhancement

#12 feat: 독서실 자리 예약 관련 Entity 작성
  src/main/java/com/ll/townforest/boundedContext/library/entity/Library.java
  src/main/java/com/ll/townforest/boundedContext/library/entity/LibraryHistory.java
  src/main/java/com/ll/townforest/boundedContext/library/entity/Seat.java
Labels: enhancement

#13 feat : gym 관련 엔티티 생성
  src/main/java/com/ll/townforest/boundedContext/gym/entity/Gym.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymHistory.java
  src/main/java/com/ll/townforest/boundedContext/gym/entity/GymMembership.java
Labels: enhancement

#15 Enhancement14/init data
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/boundedContext/account/repository/AccountRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/entity/Apt.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptAccountHouseRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptAccountRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/HouseRepository.java
  src/main/resources/application.yml
Labels: bug, enhancement

#21 Enhancement17/init data
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/boundedContext/library/entity/Library.java
  src/main/java/com/ll/townforest/boundedContext/library/repository/LibraryHistoryRepository.java
  src/main/java/com/ll/townforest/boundedContext/library/repository/LibraryRepository.java
  src/main/java/com/ll/townforest/boundedContext/library/repository/SeatRepository.java
  src/main/resources/static/librarySeat.png
Labels: enhancement

#23 Enhancement18/account
  src/main/java/com/ll/townforest/boundedContext/account/controller/AccountController.java
  src/main/resources/templates/account/login.html
  src/test/java/com/ll/townforest/boundedContext/account/controller/AccountControllerTests.java
Labels: enhancement

#22 Enhancement16/gym
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/boundedContext/gym/controller/GymController.java
  src/main/java/com/ll/townforest/boundedContext/gym/repository/GymRepository.java
  src/main/resources/templates/gym/gym.html
Labels: enhancement

#28 Enhancement19/vehicle
  src/main/java/com/ll/townforest/boundedContext/maintenance/controller/VehicleController.java
  src/main/resources/templates/maintenance/vehicle.html
Labels: enhancement

#27 feat : locker & refund html 작성
  src/main/java/com/ll/townforest/boundedContext/gym/controller/GymController.java
  src/main/resources/templates/gym/locker.html
  src/main/resources/templates/gym/refund.html
Labels: enhancement

#30 Enhancement20/library view
  src/main/java/com/ll/townforest/boundedContext/library/controller/LibraryController.java
  src/main/java/com/ll/townforest/boundedContext/library/entity/LibraryHistory.java
  src/main/java/com/ll/townforest/boundedContext/library/service/LibraryService.java
  src/main/resources/templates/library/booking.html
Labels: enhancement

#32 Enhancement31/guest vehicle view
  src/main/java/com/ll/townforest/boundedContext/maintenance/controller/GuestVehicleController.java
  src/main/resources/static/css/calender.css
  src/main/resources/static/js/calender.js
  src/main/resources/templates/guest/car_register.html
Labels: enhancement

#35 Enhancement24/account
  src/main/java/com/ll/townforest/base/initData/NotProd.java
  src/main/java/com/ll/townforest/base/security/CustomUserDetailsService.java
  src/main/java/com/ll/townforest/base/security/SecurityConfig.java
  src/main/java/com/ll/townforest/boundedContext/account/entity/Account.java
  src/main/java/com/ll/townforest/boundedContext/account/repository/AccountRepository.java
  src/main/resources/templates/account/login.html
  src/main/resources/templates/home/layout.html
  src/test/java/com/ll/townforest/boundedContext/account/controller/AccountControllerTests.java
Labels: enhancement

#36 Enhancement34/base
  src/main/java/com/ll/townforest/base/rq/Rq.java
  src/main/java/com/ll/townforest/base/rsData/RsData.java
  src/main/java/com/ll/townforest/boundedContext/account/service/AccountService.java
  src/main/java/com/ll/townforest/boundedContext/apt/repository/AptAccountRepository.java
  src/main/java/com/ll/townforest/boundedContext/apt/service/AptAccountService.java
  src/main/java/com/ll/townforest/standard/util/Ut.java
  src/main/resources/static/common/toastr.js
  src/main/resources/templates/common/js.html
  src/main/resources/templates/home/layout.html
Labels: enhancement

#39 Enhancement37/join
  src/main/java/com/ll/townforest/boundedContext/account/controller/AccountController.java
  src/main/resources/templates/account/join.html
  src/main/resources/templates/account/login.html
  src/main/resources/templates/home/layout.html
  src/test/java/com/ll/townforest/boundedContext/account/controller/AccountControllerTests.java
Labels: enhancement

#40 Enhancement33/library booking
  src/main/java/com/ll/townforest/base/rq/Rq.java
  src/main/java/com/ll/townforest/boundedContext/library/controller/LibraryController.java
  src/main/java/com/ll/townforest/boundedContext/library/entity/Seat.java
  src/main/java/com/ll/townforest/boundedContext/library/repository/LibraryHistoryRepository.java
  src/main/java/com/ll/townforest/boundedContext/library/repository/SeatRepository.java
  src/main/java/com/ll/townforest/boundedContext/library/service/LibraryService.java
  src/main/resources/templates/home/main.html
  src/main/resources/templates/library/booking.html
  src/test/java/com/ll/townforest/boundedContext/library/controller/LibraryControllerTests.java
Labels: enhancement

#45 Enhancement42/library cancel
  src/main/java/com/ll/townforest/boundedContext/library/controller/LibraryController.java
  src/main/java/com/ll/townforest/boundedContext/library/service/LibraryService.java
  src/main/resources/templates/library/booking.html
  src/test/java/com/ll/townforest/boundedContext/library/controller/LibraryControllerTests.java
Labels: enhancement
